### ISSUE TITLE
Inbound liquidity solutions

### ISSUE THREAD

**Issue by JosephGoulden** [kuutamolabs/lightning-knd#218]
Something like https://voltage.cloud/blog/voltage-announcements/introducing-flow-v2/

Use HTLCIntercepted event in LDK to create just in time channels.

**Comment by paulmattei** [comment]
https://github.com/BitcoinAndLightningLayerSpecs/lsp/pull/22

**Comment by paulmattei** [comment]
will be addressed with LSPS
