### ISSUE TITLE
LSPS0 - Feature bit

### ISSUE THREAD

**Issue by JosephGoulden** [kuutamolabs/lightning-knd#341]
Implement the groundwork for enabling the [LSP0 feauture bit](https://github.com/BitcoinAndLightningLayerSpecs/lsp/tree/main/LSPS0#lightning-feature-bit).

The following is copied from [LSP0 LDK](https://github.com/BitcoinAndLightningLayerSpecs/lsp/tree/main/LSPS0#ldk)

`LDK as of 0.0.114 requires that you create a delegating implementation of the RoutingMessageHandler trait in order to change the init and node_announcement feature bits for LSPS LSP implementations. You should implement a type that contains an instance of the LDK-provided P2PGossipSync object (or if you want something for more general use, itself contains an instance of another object with the RoutingMessageHandler), and whose implementation of RoutingMessageHandler simply forwards most of the function calls to the contained instance.

The only non-delegating functions would be provided_node_features and provided_init_features. The delegating function would call the corresponding function on the contained instance, then serialize the returned Features<T> object via Writeable::encode. The serialized vector of bytes encodes the 16-bit big-endian length, followed by the feature bits vector. The feature bits vector needs to be extended to at least 92 bytes, packing 0x00 bytes at the front of the vector if its length is increased, and the byte at length - 92 should be ORed with 0x2. Then if the length was changed, the 16-bit big-endian length needs to be updated. The 16-bit big-endian length is concatenated with the feature bits vector, then fed into a Read object, then a new InitFeatures or NodeFeatures is Readable::read from the modified feature bits serialization vector.`

Some new automated tests will be required. If its possible to run the MessageHandlers independently then that should be sufficient otherwise the end to end smoke tests should be used (with the feature enabled).

**Comment by JosephGoulden** [comment]
I don't think all that is necessary. 

LiquidityManager implements CustomMessageHandler. Our type alias LdkPeerManager points to SimpleArcPeerManager which has a hardcoded generic parameter IgnoringMessageHandler. We want to use LiquidityManager as our CHM instead of IgnoringMessageHandler. So we just need to combine the generic parameters from SimpleArcPeerManager into our LdkPeerManager.

We should not need to rewrite our other PeerManager, implement any MessageHandlers or rewrite the logger.

**Comment by yanganto** [comment]
Hmm, I find out the point I missed and why I think we need `ChannelMessageHandler` and so on.

The functions to enable feature bit are`provided_node_features` and `provided_init_features`.  These are not in the `CustomMessageHandler` of the current latest version.
https://docs.rs/lightning/0.0.115/lightning/ln/msgs/trait.ChannelMessageHandler.html#tymethod.provided_node_features
https://docs.rs/lightning/0.0.115/lightning/ln/msgs/trait.ChannelMessageHandler.html#tymethod.provided_init_features
https://docs.rs/lightning/0.0.115/lightning/ln/peer_handler/trait.CustomMessageHandler.html

The way only use a `CustomMessageHandler` to provide an LSP handler needs an unstable version after https://github.com/lightningdevkit/rust-lightning/pull/2204 (which will be release in 0.0.116, it now is 57% complete)

We can do that, we need to use unstable commit first, and then use a `CustomMessageHandler` with LSP will be easy.

**Comment by paulmattei** [comment]
Adding: #342, #343

**Comment by yanganto** [comment]
In the unstable version, the good things are the `provided_node_features` and `provided_init_features` already moved in the customized handler. 

But the things I mentioned in https://github.com/kuutamolabs/lightning-knd/issues/341#issuecomment-1596753330 are almost the same in unstable.

We are using `SimpleArcPeerManager` (which is using IgnoringMessageHandler not a customized handler).

If we only change the customized handler here.
https://github.com/kuutamolabs/lightning-knd/blob/e4358864d602560aae9c92a85b3eb11bef81fd4f/kld/src/ldk/controller.rs#L656-L657

We can not compile because the type does not match in SimpleArcPeerManager here.
https://github.com/kuutamolabs/lightning-knd/blob/e4358864d602560aae9c92a85b3eb11bef81fd4f/kld/src/ldk/controller.rs#L659-L660

Eventually, We still implement and eliminate the `SimpleArc*` type.
