### ISSUE TITLE
Handle the unreachable condition

### ISSUE THREAD

**Issue by yanganto** [kuutamolabs/lightning-knd#374]
Use `std::unreachable` to handle the unreachable condition
https://github.com/kuutamolabs/lightning-knd/blob/08cacfd1b5f594b932d5b38f5dd80d3c68c2b0d1/kld/src/ldk/event_handler.rs#L173

change to

```rust
unreachable!("we don't set manually_accept_inbound_channels")
```

**Comment by JosephGoulden** [comment]
fixed in #391
