### ISSUE TITLE
cockroachdb updates

### ISSUE THREAD

**Issue by Mic92** [kuutamolabs/lightning-knd#413]
This repo is lacking a bit behind: https://github.com/cockroachdb/cockroach/tags

**Comment by Mic92** [comment]
https://github.com/kuutamolabs/lightning-knd/blob/main/nix/pkgs/cockroachdb.nix

**Comment by Mic92** [comment]
Use `nix-prefetch-url <url>` to compute the url for darwin, if you don't have access to it.

**Comment by paulmattei** [comment]
https://github.com/kuutamolabs/lightning-knd/pull/375/commits/ff71c56350e02c19569e2ba518f227e056a40dcf
