### ISSUE TITLE
`secret_directory` setting does not work

### ISSUE THREAD

**Issue by yanganto** [kuutamolabs/lightning-knd#416]
Set up `secret_directory` and `kld-mgr install`, the secret directory still uses `secrets` (the default one).

**Comment by paulmattei** [comment]
@yanganto Which PR was this fixed in?

**Comment by paulmattei** [comment]
Ok got it , thanks! to avoid confusion in future please close as 'won't fix' rather than 'completed' and small explanation like above is helpful for those following along.
