### ISSUE TITLE
Disk encryption when mgr install

### ISSUE THREAD

**Issue by yanganto** [kuutamolabs/lightning-knd#530]
- Generate disk encryption key by mgr
- `initrd` load the sshd and load the common modules (intel 2 or 3, kvm, Realtek, and the one AWS and Google using.)
- `sudo inxi --network-advanced` (these drivers do not need to be included, ex:r8169 in following example), and ignored the wifi network cards
Network:   Device-1: Realtek RTLxxx PCI Express Gigabit Ethernet driver: r8169
           IF: enp6s0f1 state: down mac: 00:00..
           Device-2: Intel Wi-Fi 6 AXXXX driver: iwlwifi
           IF: wlp7s0 state: up mac: 00:00..
           IF-ID-1: virbr0 state: down mac: 00
- Check the default network card, and only load that one (next version)

ref:
 https://nixos.wiki/wiki/Remote_LUKS_Unlocking

**Comment by Lassulus** [comment]
draft PR for the nixos config https://github.com/kuutamolabs/lightning-knd/pull/496

**Comment by paulmattei** [comment]
completed: https://github.com/kuutamolabs/lightning-knd/pull/496
