### ISSUE TITLE
When externally accessing kld-cli, local access isn't working

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/lightning-knd#546]
```
[root@kld-00:~]# kld-cli get-info
Error executing command: error sending request for url (https://127.0.0.1:2244/v1/getinfo): error trying to connect: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1889: (IP address mismatch)
```

**Comment by yanganto** [comment]
Is this in the current latest main branch?

There is a test that always checks the `kld-cli get-info` work locally, after starting a fresh `kld`.
https://github.com/kuutamolabs/lightning-knd/blob/82085e72ee44fc4b33d62d5693dc64dcae9d714d/nix/modules/tests/kld.nix#L64

**Comment by paulmattei** [comment]
No it's an old branch. Here as a reminder, doesn't need investigating right now.

**Comment by paulmattei** [comment]
This is working
